// Generated by CoffeeScript 1.7.1
(function() {
  var pagseguro, req, xml2js, xmlBuilder;

  req = require('request');

  xml2js = require('xml2js');

  xmlBuilder = new xml2js.Builder();

  pagseguro = (function() {
    function pagseguro(email, token) {
      this.email = email;
      this.token = token;
      this.obj = new Object;
      this.xml = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>';
      return this;
    }

    pagseguro.prototype.currency = function(cur) {
      this.obj['currency'] = cur;
      return this;
    };

    pagseguro.prototype.reference = function(ref) {
      this.obj['reference'] = ref;
      return this;
    };

    pagseguro.prototype.addItem = function(item) {
      if (!this.obj['items']) {
        this.obj['items'] = new Array;
      }
      this.obj.items.push({
        item: item
      });
      return this;
    };

    pagseguro.prototype.buyer = function(obj) {
      this.obj['sender'] = new Object;
      this.obj.sender['name'] = obj.name;
      this.obj.sender['email'] = obj.email;
      this.obj.sender['phone'] = new Object;
      this.obj.sender.phone['areaCode'] = obj.phoneAreaCode;
      this.obj.sender.phone['number'] = obj.phoneNumber;
      return this;
    };

    pagseguro.prototype.shipping = function(obj) {
      this.obj['shipping'] = new Object;
      this.obj.shipping['type'] = obj.type;
      this.obj.shipping['address'] = new Object;
      this.obj.shipping.address['street'] = obj.street;
      this.obj.shipping.address['number'] = obj.number;
      if (obj.complement) {
        this.obj.shipping.address['complement'] = obj.complement;
      }
      if (obj.district) {
        this.obj.shipping.address['district'] = obj.district;
      }
      this.obj.shipping.address['postalCode'] = obj.postalCode;
      this.obj.shipping.address['city'] = obj.city;
      this.obj.shipping.address['state'] = obj.state;
      this.obj.shipping.address['country'] = obj.country;
      return this;
    };


    /*
    Configura as URLs de retorno e de notificação por pagamento
     */

    pagseguro.prototype.setRedirectURL = function(url) {
      this.obj.redirectURL = url;
      return this;
    };

    pagseguro.prototype.setNotificationURL = function(url) {
      this.obj.notificationURL = url;
      return this;
    };

    pagseguro.prototype.send = function(callback) {
      var options;
      options = {
        uri: "https://ws.pagseguro.uol.com.br/v2/checkout?email=" + this.email + "&token=" + this.token,
        method: 'POST',
        headers: {
          'Content-Type': 'application/xml; charset=UTF-8'
        },
        body: this.xml + xmlBuilder.buildObject({
          checkout: this.obj
        })
      };
      return req(options, function(err, res, body) {
        if (err || res.statusCode !== 200) {
          return callback(err);
        }
        return xml2js.parseString(body, function(err, result) {
          var code, date;
          if (err) {
            return callback(err);
          }
          code = result.checkout.code[0];
          date = new Date(result.checkout.date[0]);
          return callback(null, {
            code: code,
            date: date,
            url: "https://pagseguro.uol.com.br/v2/checkout/payment.html?code=" + code
          });
        });
      });
    };

    return pagseguro;

  })();

  module.exports = pagseguro;

}).call(this);
